# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# SDK publishing
GROUP=xyz.clppr
VERSION_NAME=1.0.0
POM_ARTIFACT_ID=clippr-sdk
POM_NAME=Clippr SDK
POM_DESCRIPTION=Deep linking and mobile attribution SDK for Android
POM_URL=https://github.com/nexlabstudio/clippr-android
POM_SCM_URL=https://github.com/nexlabstudio/clippr-android
POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT
POM_DEVELOPER_ID=clippr
POM_DEVELOPER_NAME=Nexlab Studio
